### ISSUE TITLE
Failed to Register RandomizedRound

### ISSUE THREAD

**Issue by MrWomanStealer** [Darinsky/MoreGamemodes#1]
Hey there! There seems to be an issue with the mod.
Notably:
![image](https://github.com/Darinsky/MoreGamemodes/assets/62660100/d8360515-336c-48f4-90f5-07b3b32d9167)
One Red Bloon mode isn't seen, nor is baby mode and a few others.

**Comment by MrWomanStealer** [comment]
Hey there! Got an error code:
```
[17.02.06.518] Failed to load all types in assembly MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null due to: Unable to load one or more of the requested types.
Method 'ModifyBaseGameModeModel' in type 'AllFortifiedGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'MegaChimps' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SupportOnly' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'StrongerBloons' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'RandomizedRounds' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BabyMode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SmallTowers' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'Inflation' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'OneRedBloon' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BossRushGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ModifyBaseGameModeModel' in type 'AllFortifiedGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'MegaChimps' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SupportOnly' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'StrongerBloons' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'RandomizedRounds' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BabyMode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SmallTowers' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'Inflation' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'OneRedBloon' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BossRushGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MelonLoader.MelonUtils.GetValidTypes(Assembly asm, LemonFunc`2 predicate) in D:\a\MelonLoader\MelonLoader\MelonLoader\MelonUtils.cs:line 257
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'AllFortifiedGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'MegaChimps' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'SupportOnly' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'StrongerBloons' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'RandomizedRounds' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'BabyMode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'SmallTowers' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'Inflation' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'OneRedBloon' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'BossRushGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
[17.02.07.767] [BloonsTD6_Mod_Helper] Failed to load all types in assembly MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null due to: Unable to load one or more of the requested types.
Method 'ModifyBaseGameModeModel' in type 'AllFortifiedGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'MegaChimps' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SupportOnly' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'StrongerBloons' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'RandomizedRounds' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BabyMode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SmallTowers' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'Inflation' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'OneRedBloon' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BossRushGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ModifyBaseGameModeModel' in type 'AllFortifiedGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'MegaChimps' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SupportOnly' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'StrongerBloons' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'RandomizedRounds' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BabyMode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SmallTowers' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'Inflation' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'OneRedBloon' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BossRushGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MelonLoader.MelonUtils.GetValidTypes(Assembly asm, LemonFunc`2 predicate) in D:\a\MelonLoader\MelonLoader\MelonLoader\MelonUtils.cs:line 257
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'AllFortifiedGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'MegaChimps' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'SupportOnly' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'StrongerBloons' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'RandomizedRounds' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'BabyMode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'SmallTowers' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'Inflation' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'OneRedBloon' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'BossRushGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
[17.02.07.777] [BloonsTD6_Mod_Helper] Failed to load all types in assembly MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null due to: Unable to load one or more of the requested types.
Method 'ModifyBaseGameModeModel' in type 'AllFortifiedGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'MegaChimps' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SupportOnly' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'StrongerBloons' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'RandomizedRounds' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BabyMode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SmallTowers' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'Inflation' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'OneRedBloon' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BossRushGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ModifyBaseGameModeModel' in type 'AllFortifiedGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'MegaChimps' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SupportOnly' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'StrongerBloons' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'RandomizedRounds' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BabyMode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'SmallTowers' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'Inflation' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'OneRedBloon' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ModifyBaseGameModeModel' in type 'BossRushGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MelonLoader.MelonUtils.GetValidTypes(Assembly asm, LemonFunc`2 predicate) in D:\a\MelonLoader\MelonLoader\MelonLoader\MelonUtils.cs:line 257
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'AllFortifiedGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'MegaChimps' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'SupportOnly' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'StrongerBloons' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'RandomizedRounds' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'BabyMode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'SmallTowers' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'Inflation' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'OneRedBloon' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ModifyBaseGameModeModel' in type 'BossRushGamemode' from assembly 'MoreGameModes, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Setting breakpad minidump AppID = 960090
Steam_SetMinidumpSteamID:  Caching Steam ID:  76561199014928742 [API loaded no]
[17.02.11.822] [BloonsTD6_Mod_Helper] Finished getting mods from github, found 192 mods in 4,1 seconds
[17.02.21.448] [BloonsTD6_Mod_Helper] Registering ModContent for BloonsTD6 Mod Helper...
[17.02.21.450] [BloonsTD6_Mod_Helper] Registering ModContent for Detailed Descriptions...
[17.02.21.461] [BloonsTD6_Mod_Helper] Registering ModContent for Gamemodes++...
[17.02.22.295] [BloonsTD6_Mod_Helper] Failed to modify round 0 for round set MoreGameModes-RandomizedRound
[17.02.22.295] [BloonsTD6_Mod_Helper] Failed to register MoreGameModes-RandomizedRound
[17.02.22.298] [BloonsTD6_Mod_Helper] System.MissingMethodException: Method not found: 'Il2CppInterop.Runtime.InteropTypes.Arrays.Il2CppReferenceArray`1<Il2CppAssets.Scripts.Models.Rounds.RoundSetModel> Il2CppAssets.Scripts.Models.GameModel.get_roundSets()'.
   at MoreGameModes.MoreGameModes.RandomizedRound.ModifyRoundModels(RoundModel roundModel, Int32 round)
   at BTD_Mod_Helper.Api.Bloons.ModRoundSet.Register()
   at BTD_Mod_Helper.Api.ModContentTask.Coroutine()+MoveNext()
[17.02.22.425] [BloonsTD6_Mod_Helper] Successfully saved mod settings
```

**Comment by Darinsky** [comment]
yeah, Working on a fix for random rounds
